from __future__ import annotations

STATE_MAGIC = b"RG1S"
KEYDIST_MAGIC = b"RG1K"
MSG_MAGIC = 0x4731

STATE_VERSION = 1
MEMBER_ENTRY_SIZE = 68
ED25519_SIG_SIZE = 64
X25519_PUB_SIZE = 32
ED25519_PUB_SIZE = 32
RNS_PUBLIC_KEY_SIZE = 64
HASH16 = 16
HASH32 = 32
AEAD_TAG_SIZE = 16
SEAL_PLAINTEXT_SIZE = 52
SEAL_BLOB_SIZE = 100
KEYDIST_FIXED_BODY = 58
KEYDIST_FIXED = KEYDIST_FIXED_BODY + ED25519_SIG_SIZE
STATE_FIXED_BODY = 140
STATE_FIXED_WITH_SIG = STATE_FIXED_BODY + ED25519_SIG_SIZE

MSG_HEADER_COUNTER = 32
MSG_HEADER_XCHACHA = 56

EPOCH_POLICY_TIME_BUCKET = 1
EPOCH_POLICY_LOCAL_COUNTER = 2

FLAG_REKEY = 0x0001
STATE_KNOWN_FLAGS = FLAG_REKEY

MSG_FLAG_HAS_SIG = 0x01
MSG_KNOWN_FLAGS = MSG_FLAG_HAS_SIG
MSG_FORMAT_COUNTER = 1
MSG_FORMAT_XCHACHA = 2

MAX_MEMBERS = 16
RECOMMENDED_MEMBERS_SLOW_RADIO = 8
REPLAY_WINDOW_MIN = 1024

MSG_MIN_FORMAT1 = MSG_HEADER_COUNTER + AEAD_TAG_SIZE
MSG_MIN_FORMAT2 = MSG_HEADER_XCHACHA + AEAD_TAG_SIZE
MSG_MIN_FORMAT1_SIGNED = MSG_MIN_FORMAT1 + ED25519_SIG_SIZE
MSG_MIN_FORMAT2_SIGNED = MSG_MIN_FORMAT2 + ED25519_SIG_SIZE

LABEL_GRS = b"RGKD1-GRS"
LABEL_EPOCH = b"RGKD1-EPOCH"
LABEL_SENDER = b"RGKD1-SENDER"
LABEL_MSG = b"RGKD1-MSG"
LABEL_SEAL = b"RGKD1-SEAL"
LABEL_STATE = b"RGKD1-STATE"
LABEL_NONCE = b"RGKD1-NONCE"
