from __future__ import annotations

STATE_MAGIC = b"RG1S"
KEYDIST_MAGIC = b"RG1K"
MSG_MAGIC = 0x4731

STATE_VERSION = 1
MEMBER_ENTRY_SIZE = 68
ED25519_SIG_SIZE = 64
X25519_PUB_SIZE = 32
ED25519_PUB_SIZE = 32
RNS_PUBLIC_KEY_SIZE = 64
HASH16 = 16
HASH32 = 32

AES_BLOCK = 16
TOKEN_KEY_SIZE = 64
TOKEN_OVERHEAD = 48
TOKEN_HMAC_SIZE = 32
TOKEN_IV_SIZE = 16

SEAL_PLAINTEXT_SIZE = 52
# eph_pub (32) + IV (16) + AES-CBC(PKCS7(52)->64) + HMAC (32)
SEAL_TOKEN_SIZE = TOKEN_IV_SIZE + 64 + TOKEN_HMAC_SIZE
SEAL_BLOB_SIZE = X25519_PUB_SIZE + SEAL_TOKEN_SIZE

KEYDIST_FIXED_BODY = 58
KEYDIST_FIXED = KEYDIST_FIXED_BODY + ED25519_SIG_SIZE
STATE_FIXED_BODY = 140
STATE_FIXED_WITH_SIG = STATE_FIXED_BODY + ED25519_SIG_SIZE

MSG_HEADER = 32

EPOCH_POLICY_TIME_BUCKET = 1
EPOCH_POLICY_LOCAL_COUNTER = 2

FLAG_REKEY = 0x0001
STATE_KNOWN_FLAGS = FLAG_REKEY

MSG_FLAG_HAS_SIG = 0x01
MSG_KNOWN_FLAGS = MSG_FLAG_HAS_SIG
MSG_FORMAT_TOKEN = 1

MAX_MEMBERS = 16
RECOMMENDED_MEMBERS_SLOW_RADIO = 8
REPLAY_WINDOW_MIN = 1024

# Empty plaintext pads to one AES block under PKCS7.
MSG_MIN_TOKEN = TOKEN_OVERHEAD + AES_BLOCK
MSG_MIN_UNSIGNED = MSG_HEADER + MSG_MIN_TOKEN
MSG_MIN_SIGNED = MSG_MIN_UNSIGNED + ED25519_SIG_SIZE

LABEL_GRS = b"RGKD1-GRS"
LABEL_EPOCH = b"RGKD1-EPOCH"
LABEL_SENDER = b"RGKD1-SENDER"
LABEL_MSG = b"RGKD1-MSG"
LABEL_SEAL = b"RGKD1-SEAL"
LABEL_STATE = b"RGKD1-STATE"
